"""Core primitives (zero external deps)."""
from gg_relay.core.domain import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    SessionState,
    SessionSummary,
    is_legal_transition,
)
from gg_relay.core.event_bus import EventBus
from gg_relay.core.events import (
    DeliveryTier,
    Heartbeat,
    HITLRequested,
    HITLResolved,
    InstallDone,
    InstallError,
    RelayEvent,
    RelayEventT,
    SessionCompleted,
    SessionCreated,
    SessionOutputChunk,
    SessionStateChanged,
    ToolRequested,
    ToolResolved,
    frame_to_event,
)

__all__ = [
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "DeliveryTier",
    "EventBus",
    "Heartbeat",
    "HITLRequested",
    "HITLResolved",
    "InstallDone",
    "InstallError",
    "RelayEvent",
    "RelayEventT",
    "SessionCompleted",
    "SessionCreated",
    "SessionOutputChunk",
    "SessionState",
    "SessionStateChanged",
    "SessionSummary",
    "ToolRequested",
    "ToolResolved",
    "frame_to_event",
    "is_legal_transition",
]
