"""Core primitives (zero external deps)."""
from gg_relay.core.domain import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    SessionState,
    SessionSummary,
    is_legal_transition,
)
from gg_relay.core.event_bus import EventBus
from gg_relay.core.events import (
    DeliveryTier,
    Heartbeat,
    HITLRequested,
    HITLResolved,
    InstallDone,
    InstallError,
    RelayEvent,
    RelayEventT,
    SessionCompleted,
    SessionCreated,
    SessionOutputChunk,
    SessionStateChanged,
    ToolRequested,
    ToolResolved,
    frame_to_event,
)
from gg_relay.core.exceptions import (
    ApiKeyConflictError,
    DurableEventDropError,
    HITLAlreadyResolved,
    LastAdminError,
    RetryConfigError,
    SDKConnectError,
    SDKError,
    SDKPermissionError,
    SDKQueryError,
    SDKTimeoutError,
    SDKTransportError,
    SDKUnknownError,
    SelfRevokeError,
    TemplateConflictError,
    classify_sdk_error,
)
from gg_relay.core.protocol import DurableEventStore

__all__ = [
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "ApiKeyConflictError",
    "DeliveryTier",
    "DurableEventDropError",
    "DurableEventStore",
    "EventBus",
    "HITLAlreadyResolved",
    "Heartbeat",
    "HITLRequested",
    "HITLResolved",
    "InstallDone",
    "InstallError",
    "LastAdminError",
    "RelayEvent",
    "RelayEventT",
    "RetryConfigError",
    "SDKConnectError",
    "SDKError",
    "SDKPermissionError",
    "SDKQueryError",
    "SDKTimeoutError",
    "SDKTransportError",
    "SDKUnknownError",
    "SelfRevokeError",
    "SessionCompleted",
    "SessionCreated",
    "SessionOutputChunk",
    "SessionState",
    "SessionStateChanged",
    "SessionSummary",
    "TemplateConflictError",
    "ToolRequested",
    "ToolResolved",
    "classify_sdk_error",
    "frame_to_event",
    "is_legal_transition",
]
